    isp_debayer __(.axis_rx_clk_i( ),
        .axis_rx_arstn_i( ),
        .axis_tx_clk_i( ),
        .axis_tx_arstn_i( ),
        .rx_tdata_i( ),
        .rx_tuser_i( ),
        .rx_tlast_i( ),
        .rx_tvalid_i( ),
        .rx_tready_o( ),
        .tx_tready_i( ),
        .tx_tdata_o( ),
        .tx_tvalid_o( ),
        .tx_tlast_o( ),
        .tx_tuser_o( ));
