/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.0.0.01
    2026 03 05 19:51:01
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module mipi_csi_rx (sync_clk_i, sync_rst_i, ready_o, clk_fr_i, clk_byte_o,
    reset_fr_n_i, pll_lock_i, clk_p_io, clk_n_io, d_p_io, d_n_io,
    axis_vid_clk_i, axis_vid_rstn_i, axis_vid_tready_i, axis_vid_tvalid_o,
    axis_vid_tdata_o, axis_vid_tuser_o, axis_vid_tlast_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  sync_clk_i;
    input  sync_rst_i;
    output  ready_o;
    input  clk_fr_i;
    output  clk_byte_o;
    input  reset_fr_n_i;
    input  pll_lock_i;
    inout  clk_p_io;
    inout  clk_n_io;
    inout  [3:0]  d_p_io;
    inout  [3:0]  d_n_io;
    input  axis_vid_clk_i;
    input  axis_vid_rstn_i;
    input  axis_vid_tready_i;
    output  axis_vid_tvalid_o;
    output  [63:0]  axis_vid_tdata_o;
    output  [2:0]  axis_vid_tuser_o;
    output  axis_vid_tlast_o;
endmodule