--  >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
--	  ------------------------------------------------------------------
--	  Copyright(c) 2019 - 2026 by Lattice Semiconductor Corporation
--      ALL RIGHTS RESERVED
--	  ------------------------------------------------------------------

--	  IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
--DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

--	   Lattice grants permission to use this code pursuant to the
--       terms of the Lattice Propel License Agreement.

--     DISCLAIMER :

--       LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
--EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE PROPEL
--LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE SPECIFICALLY
--DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A
--PARTICULAR PURPOSE.LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED
--HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT LICENSEE'S OPERATION OF
--ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
--UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS HEREIN WILL BE CORRECTED.
--LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE ITS
--INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE, AND RESULTS 
--OBTAINED THEREFROM.LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS 
--CONTENTS PROVING DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH 
--EVENT, LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, 
--SERVICE, CORRECTION, OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR 
--ASSOCIATED WITH THE SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY 
--PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, 
--INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS 
--CONTENTS, EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH 
--DAMAGES.LATTICE'S SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH 
--ABOVE.LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS 
--OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY 
--RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY THE 
--USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE USE OF 
--FORMAL SOFTWARE VALIDATION METHODS.

--     ------------------------------------------------------------------

--VHDL instantiation template

component mipi_csi_to_pcie is
    port (d_n_io: inout std_logic_vector(3 downto 0);
        d_p_io: inout std_logic_vector(3 downto 0);
        pcie_status_led_o: out std_logic_vector(4 downto 0);
        cam_reset_n_o: out std_logic;
        cam_scl_io: inout std_logic;
        cam_sda_io: inout std_logic;
        clk_125mhz: in std_logic;
        clk_n_io: inout std_logic;
        clk_p_io: inout std_logic;
        cpnx_versa_pcie_clk_sel_o: out std_logic;
        cpnx_versa_pcie_sw1_pd_o: out std_logic;
        cpnx_versa_pcie_sw2_pd_o: out std_logic;
        cpnx_versa_pcie_sw_sel_o: out std_logic;
        pcie_perst_n_i: in std_logic;
        pcie_refclkn_i: in std_logic;
        pcie_refclkp_i: in std_logic;
        pcie_sd0_refret_i: in std_logic;
        pcie_sd0_rext_i: in std_logic;
        pcie_sd0_rxdn_i: in std_logic;
        pcie_sd0_rxdp_i: in std_logic;
        pcie_sd0_txdn_o: out std_logic;
        pcie_sd0_txdp_o: out std_logic;
        pcie_sd1_refret_i: in std_logic;
        pcie_sd1_rext_i: in std_logic;
        pcie_sd1_rxdn_i: in std_logic;
        pcie_sd1_rxdp_i: in std_logic;
        pcie_sd1_txdn_o: out std_logic;
        pcie_sd1_txdp_o: out std_logic;
        pcie_sd2_refret_i: in std_logic;
        pcie_sd2_rext_i: in std_logic;
        pcie_sd2_rxdn_i: in std_logic;
        pcie_sd2_rxdp_i: in std_logic;
        pcie_sd2_txdn_o: out std_logic;
        pcie_sd2_txdp_o: out std_logic;
        pcie_sd3_refret_i: in std_logic;
        pcie_sd3_rext_i: in std_logic;
        pcie_sd3_rxdn_i: in std_logic;
        pcie_sd3_rxdp_i: in std_logic;
        pcie_sd3_txdn_o: out std_logic;
        pcie_sd3_txdp_o: out std_logic;
        rst_led: out std_logic;
        rst_n: in std_logic
    );
    
end component mipi_csi_to_pcie;
_inst: mipi_csi_to_pcie port map (pcie_refclkn_i => __,
                                  pcie_refclkp_i => __,
                                  cam_scl_io => __,
                                  cam_sda_io => __,
                                  d_n_io => __,
                                  d_p_io => __,
                                  cam_reset_n_o => __,
                                  clk_n_io => __,
                                  clk_p_io => __,
                                  clk_125mhz => __);
                                  