    mipi_csi_rx __(.sync_clk_i( ),
        .sync_rst_i( ),
        .ready_o( ),
        .clk_fr_i( ),
        .clk_byte_o( ),
        .reset_fr_n_i( ),
        .pll_lock_i( ),
        .clk_p_io( ),
        .clk_n_io( ),
        .d_p_io( ),
        .d_n_io( ),
        .axis_vid_clk_i( ),
        .axis_vid_rstn_i( ),
        .axis_vid_tready_i( ),
        .axis_vid_tvalid_o( ),
        .axis_vid_tdata_o( ),
        .axis_vid_tuser_o( ),
        .axis_vid_tlast_o( ));
