/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.4.0.01
    2026 03 05 19:51:24
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module isp_awb (axis_rx_clk_i, axis_rx_arstn_i, axis_tx_clk_i, axis_tx_arstn_i,
    rx_tdata_i, rx_tuser_i, rx_tlast_i, rx_tvalid_i, rx_tready_o, tx_tready_i,
    tx_tdata_o, tx_tvalid_o, tx_tlast_o, tx_tuser_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  axis_rx_clk_i;
    input  axis_rx_arstn_i;
    input  axis_tx_clk_i;
    input  axis_tx_arstn_i;
    input  [95:0]  rx_tdata_i;
    input  [1:0]  rx_tuser_i;
    input  rx_tlast_i;
    input  rx_tvalid_i;
    output  rx_tready_o;
    input  tx_tready_i;
    output  [95:0]  tx_tdata_o;
    output  tx_tvalid_o;
    output  tx_tlast_o;
    output  [1:0]  tx_tuser_o;
endmodule