/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.9.1
    2026 03 05 19:51:40
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module sys_clk_pll (clki_i, rstn_i, clkop_o, clkos_o, clkos2_o, clkos3_o,
    lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    input  rstn_i;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
    output  clkos3_o;
    output  lock_o;
endmodule