/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2026.1.0.2605310407
    Soft IP Version: 4.1.0
    2026 06 30 22:20:55
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pcie_axis_dma (link0_rxp_i, link0_rxn_i, refclkp_i, refclkn_i,
    link0_txp_o, link0_txn_o, refret_i, rext_i, sys_clk_i, acjtag_mode_i,
    use_refmux_i, sd_pll_refclk_i, diffioclksel_i, clksel_i, link0_aux_clk_i,
    link0_perst_n_i, link0_rst_usr_n_i, link0_clk_usr_o, link0_pl_link_up_o,
    link0_dl_link_up_o, link0_tl_link_up_o, link0_user_aux_power_detected_i,
    link0_user_transactions_pending_i, usr_lmmi_clk_i, usr_lmmi_resetn_i,
    usr_lmmi_request_i, usr_lmmi_wr_rdn_i, usr_lmmi_wdata_i, usr_lmmi_offset_i,
    usr_lmmi_rdata_o, usr_lmmi_rdata_valid_o, usr_lmmi_ready_o, clk_usr_div2_i,
    tx0_dma_axist_tready_o, tx0_dma_axist_tvalid_i, tx0_dma_axist_tlast_i,
    tx0_dma_axist_tdata_i, m0_aximm_awaddr_o, m0_aximm_awprot_o,
    m0_aximm_arprot_o, m0_aximm_arqos_o, m0_aximm_arcache_o, m0_aximm_aruser_o,
    m0_aximm_arlock_o, m0_aximm_awvalid_o, m0_aximm_wdata_o, m0_aximm_wstrb_o,
    m0_aximm_wvalid_o, m0_aximm_bready_o, m0_aximm_araddr_o,
    m0_aximm_arvalid_o, m0_aximm_rready_o, m0_aximm_awid_o, m0_aximm_awlen_o,
    m0_aximm_awsize_o, m0_aximm_awburst_o, m0_aximm_awlock_o,
    m0_aximm_awcache_o, m0_aximm_wlast_o, m0_aximm_arid_o, m0_aximm_arlen_o,
    m0_aximm_arsize_o, m0_aximm_arburst_o, m0_aximm_awready_i,
    m0_aximm_wready_i, m0_aximm_bresp_i, m0_aximm_bvalid_i, m0_aximm_arready_i,
    m0_aximm_rdata_i, m0_aximm_rresp_i, m0_aximm_rvalid_i, m0_aximm_bid_i,
    m0_aximm_rid_i, m0_aximm_rlast_i, usr_int_req_i, usr_int_ack_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  [3:0]  link0_rxp_i;
    input  [3:0]  link0_rxn_i;
    input  refclkp_i;
    input  refclkn_i;
    output  [3:0]  link0_txp_o;
    output  [3:0]  link0_txn_o;
    input  [3:0]  refret_i;
    input  [3:0]  rext_i;
    input  sys_clk_i;
    input  acjtag_mode_i;
    input  use_refmux_i;
    input  sd_pll_refclk_i;
    input  diffioclksel_i;
    input  [1:0]  clksel_i;
    input  link0_aux_clk_i;
    input  link0_perst_n_i;
    input  link0_rst_usr_n_i;
    output  link0_clk_usr_o;
    output  link0_pl_link_up_o;
    output  link0_dl_link_up_o;
    output  link0_tl_link_up_o;
    input  link0_user_aux_power_detected_i;
    input  [0:0]  link0_user_transactions_pending_i;
    input  usr_lmmi_clk_i;
    input  usr_lmmi_resetn_i;
    input  [4:0]  usr_lmmi_request_i;
    input  usr_lmmi_wr_rdn_i;
    input  [31:0]  usr_lmmi_wdata_i;
    input  [16:0]  usr_lmmi_offset_i;
    output  [63:0]  usr_lmmi_rdata_o;
    output  [4:0]  usr_lmmi_rdata_valid_o;
    output  [4:0]  usr_lmmi_ready_o;
    input  clk_usr_div2_i;
    output  tx0_dma_axist_tready_o;
    input  tx0_dma_axist_tvalid_i;
    input  tx0_dma_axist_tlast_i;
    input  [255:0]  tx0_dma_axist_tdata_i;
    output  [63:0]  m0_aximm_awaddr_o;
    output  [2:0]  m0_aximm_awprot_o;
    output  [2:0]  m0_aximm_arprot_o;
    output  [3:0]  m0_aximm_arqos_o;
    output  [3:0]  m0_aximm_arcache_o;
    output  [7:0]  m0_aximm_aruser_o;
    output  m0_aximm_arlock_o;
    output  m0_aximm_awvalid_o;
    output  [31:0]  m0_aximm_wdata_o;
    output  [3:0]  m0_aximm_wstrb_o;
    output  m0_aximm_wvalid_o;
    output  m0_aximm_bready_o;
    output  [63:0]  m0_aximm_araddr_o;
    output  m0_aximm_arvalid_o;
    output  m0_aximm_rready_o;
    output  [7:0]  m0_aximm_awid_o;
    output  [7:0]  m0_aximm_awlen_o;
    output  [2:0]  m0_aximm_awsize_o;
    output  [1:0]  m0_aximm_awburst_o;
    output  m0_aximm_awlock_o;
    output  [3:0]  m0_aximm_awcache_o;
    output  m0_aximm_wlast_o;
    output  [7:0]  m0_aximm_arid_o;
    output  [7:0]  m0_aximm_arlen_o;
    output  [2:0]  m0_aximm_arsize_o;
    output  [1:0]  m0_aximm_arburst_o;
    input  m0_aximm_awready_i;
    input  m0_aximm_wready_i;
    input  [1:0]  m0_aximm_bresp_i;
    input  m0_aximm_bvalid_i;
    input  m0_aximm_arready_i;
    input  [31:0]  m0_aximm_rdata_i;
    input  [1:0]  m0_aximm_rresp_i;
    input  m0_aximm_rvalid_i;
    input  [7:0]  m0_aximm_bid_i;
    input  [7:0]  m0_aximm_rid_i;
    input  m0_aximm_rlast_i;
    input  [0:0]  usr_int_req_i;
    output  [0:0]  usr_int_ack_o;
endmodule