/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2026.1.0.2606162255
    Soft IP Version: 4.0.0
    2026 09 09 13:27:15
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module mipi_csi_rx (clk_p_io, clk_n_io, d_p_io, d_n_io, fr_clk_i, fr_rst_n_i,
    ref_clk_i, ref_rst_n_i, byte_clk_o, axis_vid_clk_i, axis_vid_rst_n_i,
    axis_vid_tready_i, axis_vid_tvalid_o, axis_vid_tdata_o, axis_vid_tuser_o,
    axis_vid_tlast_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    inout  clk_p_io;
    inout  clk_n_io;
    inout  [3:0]  d_p_io;
    inout  [3:0]  d_n_io;
    input  fr_clk_i;
    input  fr_rst_n_i;
    input  ref_clk_i;
    input  ref_rst_n_i;
    output  byte_clk_o;
    input  axis_vid_clk_i;
    input  axis_vid_rst_n_i;
    input  axis_vid_tready_i;
    output  axis_vid_tvalid_o;
    output  [63:0]  axis_vid_tdata_o;
    output  [1:0]  axis_vid_tuser_o;
    output  axis_vid_tlast_o;
endmodule