/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2026.1.0.2606162255
    Soft IP Version: 1.1.1
    2026 07 28 07:42:17
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module video_pcie_bridge (rst_n, axis_vid_clk_i, axis_vid_tvalid_i,
    axis_vid_tdata_i, axis_vid_tuser_i, axis_vid_tlast_i, axis_vid_tready_o,
    pcie_dma_clk_i, pcie_dma_tvalid_o, pcie_dma_tdata_o, pcie_dma_tlast_o,
    pcie_dma_tready_i, pcie_dma_int_req_o, pcie_dma_int_ack_i, start_streaming)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rst_n;
    input  axis_vid_clk_i;
    input  axis_vid_tvalid_i;
    input  [95:0]  axis_vid_tdata_i;
    input  [1:0]  axis_vid_tuser_i;
    input  axis_vid_tlast_i;
    output  axis_vid_tready_o;
    input  pcie_dma_clk_i;
    output  pcie_dma_tvalid_o;
    output  [255:0]  pcie_dma_tdata_o;
    output  pcie_dma_tlast_o;
    input  pcie_dma_tready_i;
    output  pcie_dma_int_req_o;
    input  pcie_dma_int_ack_i;
    output  start_streaming;
endmodule