    video_pcie_bridge __(.rst_n( ),
        .axis_vid_clk_i( ),
        .axis_vid_tvalid_i( ),
        .axis_vid_tdata_i( ),
        .axis_vid_tuser_i( ),
        .axis_vid_tlast_i( ),
        .axis_vid_tready_o( ),
        .pcie_dma_clk_i( ),
        .pcie_dma_tvalid_o( ),
        .pcie_dma_tdata_o( ),
        .pcie_dma_tlast_o( ),
        .pcie_dma_tready_i( ),
        .pcie_dma_int_req_o( ),
        .pcie_dma_int_ack_i( ),
        .start_streaming( ));
