/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.1.0
    2026 04 03 11:56:02
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module rs_pixel (src_rst_n, dest_clk, dest_rst, dest_rst_n)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  src_rst_n;
    input  dest_clk;
    output  dest_rst;
    output  dest_rst_n;
endmodule