
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.1.0
    2026 04 03 11:56:02
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="rs_pixel", LATTICE_IP_GENERATED="1" *) module rs_pixel (src_rst_n, 
        dest_clk, 
        dest_rst, 
        dest_rst_n) ;
    input src_rst_n ; 
    input dest_clk ; 
    output dest_rst ; 
    output dest_rst_n ; 
    rs_pixel_ipgen_lscc_reset #(.RESET_MODE("ASYNC"),
            .SYNC_STAGE(2),
            .SIM_ASSERT_EN(0)) lscc_reset_inst (.src_rst_n(src_rst_n), 
                .dest_clk(dest_clk), 
                .dest_rst(dest_rst), 
                .dest_rst_n(dest_rst_n)) ; 
endmodule



//---------------------------------------------------------------------
// Module: lscc_reset
//---------------------------------------------------------------------
// Copyright (c) 2024 by Lattice Semiconductor Corporation
//---------------------------------------------------------------------
//
//  Purpose:
//  Top level wrapper to select between all existing reset common modules
//  with matching metadata for easier GUI configuration.
//
//---------------------------------------------------------------------
(* LATTICE_IP_MODULE=1 *) module rs_pixel_ipgen_lscc_reset #(parameter RESET_MODE = "ASYNC", 
        parameter SYNC_STAGE = 2, 
        parameter SIM_ASSERT_EN = 1'b1) (
    input logic src_rst_n, 
    input logic dest_clk, 
    output logic dest_rst, 
    output logic dest_rst_n) ;
    generate
        if ((RESET_MODE == "ASYNC")) 
            begin : async_reset_mode
                //-------------------------------------------------------------------
                // Asynchronous Reset
                //-------------------------------------------------------------------
                rs_pixel_ipgen_lscc_reset_async #(.SYNC_STAGE(SYNC_STAGE),
                        .SIM_ASSERT_EN(SIM_ASSERT_EN)) u_lscc_reset_async (.src_rst_n(src_rst_n), 
                            .dest_clk(dest_clk), 
                            .dest_rst(dest_rst), 
                            .dest_rst_n(dest_rst_n)) ; 
            end
        else
            if ((RESET_MODE == "SYNC")) 
                begin : sync_reset_mode
                    //-------------------------------------------------------------------
                    // Synchronous Reset
                    //-------------------------------------------------------------------
                    rs_pixel_ipgen_lscc_reset_sync #(.SYNC_STAGE(SYNC_STAGE),
                            .SIM_ASSERT_EN(SIM_ASSERT_EN)) u_lscc_reset_sync (.src_rst_n(src_rst_n), 
                                .dest_clk(dest_clk), 
                                .dest_rst(dest_rst), 
                                .dest_rst_n(dest_rst_n)) ; 
                end
    endgenerate
endmodule



//---------------------------------------------------------------------
// Module: lscc_reset_async
//---------------------------------------------------------------------
// Copyright (c) 2024 by Lattice Semiconductor Corporation
//---------------------------------------------------------------------
//
//  Params:
//  + SYNC_STAGE    -   Number of register stages used in synchronizers
//                      Allowable range is from 2 to 4
//  + SIM_ASSERT_EN -   Assertion enable
//
//  Ports:
//  + src_rst_n     -   Source reset (active low)
//
//  + dest_clk      -   Destination clock
//  + dest_rst      -   Destination reset (active high)
//  + dest_rst_n    -   Destination reset (active low)
//
//---------------------------------------------------------------------
(* LATTICE_IP_MODULE=1 *) module rs_pixel_ipgen_lscc_reset_async #(parameter SYNC_STAGE = 2, 
        parameter SIM_ASSERT_EN = 1'b1) (
    input logic src_rst_n, 
    input logic dest_clk, 
    (* syn_preserve=1 *) output logic dest_rst, 
    (* syn_preserve=1 *) output logic dest_rst_n) ;
    (* syn_preserve=1 *) logic [(SYNC_STAGE - 1):0] rstn_sync ; 
    (* syn_preserve=1 *) logic [(SYNC_STAGE - 1):0] rst_sync ; 
    always_ff
        @(posedge dest_clk or 
            negedge src_rst_n)
        begin
            if ((~src_rst_n)) 
                begin
                    rstn_sync <=  {SYNC_STAGE{1'b0}} ;
                    rst_sync <=  {SYNC_STAGE{1'b1}} ;
                end
            else
                begin
                    rstn_sync <=  {rstn_sync[(SYNC_STAGE - 2):0],
                            1'b1} ;
                    rst_sync <=  {rst_sync[(SYNC_STAGE - 2):0],
                            1'b0} ;
                end
        end
    assign dest_rst_n = rstn_sync[(SYNC_STAGE - 1)] ; 
    assign dest_rst = rst_sync[(SYNC_STAGE - 1)] ; 
endmodule



//---------------------------------------------------------------------
// Module: lscc_reset_sync
//---------------------------------------------------------------------
// Copyright (c) 2024 by Lattice Semiconductor Corporation
//---------------------------------------------------------------------
//
//  Params:
//  + SYNC_STAGE    -   Number of register stages used in synchronizers
//                      Allowable range is from 2 to 4
//  + SIM_ASSERT_EN -   Assertion enable
//
//  Ports:
//  + src_rst_n     -   Source reset (active low)
//
//  + dest_clk      -   Destination clock
//  + dest_rst      -   Destination reset (active high)
//  + dest_rst_n    -   Destination reset (active low)
//
//---------------------------------------------------------------------
(* LATTICE_IP_MODULE=1 *) module rs_pixel_ipgen_lscc_reset_sync #(parameter SYNC_STAGE = 2, 
        parameter SIM_ASSERT_EN = 1'b1) (
    input logic src_rst_n, 
    input logic dest_clk, 
    output logic dest_rst, 
    output logic dest_rst_n) ;
    (* syn_preserve=1 *) logic [(SYNC_STAGE - 1):0] rstn_sync = {SYNC_STAGE{1'b1}} ; 
    (* syn_preserve=1 *) logic [(SYNC_STAGE - 1):0] rst_sync = {SYNC_STAGE{1'b0}} ; 
    always_ff
        @(posedge dest_clk)
        begin
            rstn_sync <=  {rstn_sync[(SYNC_STAGE - 2):0],
                    src_rst_n} ;
            rst_sync <=  {rst_sync[(SYNC_STAGE - 2):0],
                    (~src_rst_n)} ;
        end
    assign dest_rst = rst_sync[(SYNC_STAGE - 1)] ; 
    assign dest_rst_n = rstn_sync[(SYNC_STAGE - 1)] ; 
endmodule


